version: '3'

services:

  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - ALL
    environment:
#      change to .env
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_SHEMA}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASS}
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql


  php:
    container_name: php
    build:
      context: ./php
    volumes:
      - ../.:/var/www/ecoicity
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ../.:/var/www/ecoicity
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_USER_PASS}
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8081:80
    links:
      - db
